import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import Layout from "~/components/layout/app-layout";
import { Toaster } from "~/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontBody = Fira_Code({
  weight: ["400", "600",]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`antialiased ${fontBody.className}`}
      >
        <Layout>
          {children}
        </Layout>

        <Toaster />
      </body>
    </html>
  );
}
